import { BarChart3, Download, Edit, Plus, Search, Star, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "react-router";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { eventViewModel } from "../../components/shared/dataHelpers";
import { clubs } from "../../data/mockClubs";
import { events } from "../../data/mockEvents";
import { facultyData, healthMetrics, yearData } from "../../data/mockAnalytics";
import { students } from "../../data/mockUsers";

const COLORS = ["#7C0A02", "#D4AF37", "#374151", "#F59E0B", "#8B5CF6"];

export default function OrganizerDashboard() {
  const [activeTab, setActiveTab] = useState("published");
  const [search, setSearch] = useState("");
  const [showHealth, setShowHealth] = useState(false);
  const [showCharts, setShowCharts] = useState(false);
  const club = clubs[0];
  const clubEvents = useMemo(() => events.filter((event) => event.clubId === club.id).map(eventViewModel), [club.id]);
  const published = clubEvents.filter((event) => event.status === "published");
  const drafts = clubEvents.filter((event) => event.status === "draft");
  const followers = students.filter((student) => student.fullName.toLowerCase().includes(search.toLowerCase()) || student.faculty.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="max-w-6xl mx-auto px-4 py-6 pb-24">
      <div className="flex flex-col md:flex-row md:items-center gap-4 justify-between mb-5">
        <div className="flex items-center gap-3"><div className="w-14 h-14 bg-primary rounded-xl text-white grid place-items-center text-xl font-bold">{club.initials}</div><div><h1 className="text-2xl font-bold">{club.name}</h1><p className="text-sm text-muted-foreground">Club Management Dashboard</p></div></div>
        <div className="flex gap-3"><button onClick={() => setShowHealth(true)} className="px-4 py-3 bg-green-50 border-2 border-green-500 rounded-xl flex items-center gap-3"><span className="w-10 h-10 bg-green-500 text-white rounded-full grid place-items-center font-bold">{club.healthScore}</span><span className="text-left text-sm text-green-700">Club Health Score<br /><b>{club.healthScore}/100</b></span></button><Link to="/organizer/events/new" className="px-4 py-3 bg-primary text-primary-foreground rounded-xl flex items-center gap-2"><Plus className="w-5 h-5" />Create Event</Link></div>
      </div>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-5">{[["Total Events", 24], ["Total RSVPs", "1,247"], ["Avg Rating", "4.7"], ["Followers", club.followers.toLocaleString()]].map(([label, value]) => <div key={label} className="bg-card rounded-xl p-4 border border-border"><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p><p className="text-xs text-green-600 mt-1">+ this month</p></div>)}</div>
      <div className="flex bg-muted/50 rounded-xl p-1 mb-4 overflow-x-auto">{["published", "drafts", "followers"].map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={`flex-1 px-3 py-2 rounded-lg capitalize ${activeTab === tab ? "bg-card shadow-sm" : "text-muted-foreground"}`}>{tab}</button>)}</div>
      {activeTab === "published" && <EventTable events={published} />}
      {activeTab === "drafts" && <div className="space-y-3">{drafts.map((event) => <div key={event.id} className="bg-card rounded-xl p-4 border border-border"><h2 className="font-semibold">{event.title}</h2><p className="text-sm text-muted-foreground mb-3">{event.description}</p><div className="flex gap-2"><Link to={`/organizer/events/${event.id}/edit`} className="flex-1 px-3 py-2 bg-muted rounded-lg text-center flex justify-center gap-2"><Edit className="w-4 h-4" />Edit Draft</Link><button className="flex-1 px-3 py-2 bg-primary text-primary-foreground rounded-lg">Publish Now</button></div></div>)}</div>}
      {activeTab === "followers" && <div className="space-y-3"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" /><input value={search} onChange={(e) => setSearch(e.target.value)} className="w-full pl-10 pr-4 py-2.5 bg-card border border-border rounded-lg" placeholder="Search followers..." /></div><button onClick={() => setShowCharts(true)} className="px-4 py-2.5 bg-primary text-primary-foreground rounded-lg flex gap-2"><BarChart3 className="w-4 h-4" />Charts</button></div><table className="w-full bg-card rounded-xl border border-border overflow-hidden text-sm"><tbody>{followers.map((follower) => <tr key={follower.id} className="border-t border-border"><td className="p-3 font-medium">{follower.fullName}</td><td className="p-3 text-muted-foreground">{follower.faculty}</td><td className="p-3 text-muted-foreground">{follower.yearOfStudy}</td></tr>)}</tbody></table></div>}
      {showHealth && <HealthModal onClose={() => setShowHealth(false)} score={club.healthScore} />}
      {showCharts && <ChartModal onClose={() => setShowCharts(false)} />}
    </div>
  );
}

function EventTable({ events }) {
  const [deleteTarget, setDeleteTarget] = useState(null);
  return <div className="bg-card rounded-xl border border-border overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-muted/30"><tr><th className="p-3 text-left">Event Name</th><th className="p-3 text-left">Date</th><th className="p-3 text-left">RSVPs</th><th className="p-3 text-left">Views</th><th className="p-3 text-left">Rating</th><th className="p-3 text-left">Action</th></tr></thead><tbody>{events.map((event) => <tr key={event.id} className="border-t border-border"><td className="p-3 font-medium">{event.title}</td><td className="p-3 text-muted-foreground">{event.date}</td><td className="p-3"><span className="px-2 py-1 bg-primary/10 text-primary rounded-full">{event.rsvpCount}</span></td><td className="p-3 text-muted-foreground">{event.views}</td><td className="p-3"><Star className="w-4 h-4 text-yellow-500 fill-current inline" /> {event.rating}</td><td className="p-3 flex gap-2"><Link to={`/organizer/responses/${event.id}`} title="View responses" className="p-2 bg-primary/10 text-primary rounded-lg"><Download className="w-4 h-4" /></Link><button onClick={() => setDeleteTarget(event)} title="Delete event" className="p-2 bg-red-50 text-red-600 rounded-lg"><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table>{deleteTarget && <div className="fixed inset-0 bg-black/50 z-50 grid place-items-center p-4"><div className="bg-card rounded-2xl p-6 max-w-sm"><h2 className="text-lg font-bold mb-2">Delete event?</h2><p className="text-sm text-muted-foreground mb-6">{deleteTarget.title} has {deleteTarget.rsvpCount} RSVPs. This action is permanent in the prototype.</p><div className="flex gap-2"><button onClick={() => setDeleteTarget(null)} className="flex-1 py-3 border rounded-lg">Cancel</button><button onClick={() => setDeleteTarget(null)} className="flex-1 py-3 bg-red-600 text-white rounded-lg">Delete</button></div></div></div>}</div>;
}
function HealthModal({ score, onClose }) { return <div className="fixed inset-0 bg-black/40 z-50 flex items-end sm:items-center justify-center"><div className="bg-card rounded-t-2xl sm:rounded-2xl p-6 w-full max-w-md"><div className="text-center mb-6"><div className="w-20 h-20 bg-green-500 rounded-full text-white grid place-items-center mx-auto text-3xl font-bold">{score}</div><h2 className="text-xl font-bold mt-3">Club Health Score</h2><p className="text-sm text-muted-foreground">Performance breakdown across key metrics</p></div><div className="space-y-4">{healthMetrics.map((metric) => <div key={metric.label} className="bg-muted/30 rounded-xl p-4"><div className="flex justify-between text-sm mb-2"><span>{metric.label}</span><b style={{ color: metric.color }}>{metric.score}</b></div><div className="h-2 bg-muted rounded-full overflow-hidden"><div className="h-full" style={{ width: `${metric.score}%`, backgroundColor: metric.color }} /></div></div>)}</div><button onClick={onClose} className="w-full mt-6 px-4 py-3 bg-primary text-primary-foreground rounded-xl">Close</button></div></div>; }
function ChartModal({ onClose }) { return <div className="fixed inset-0 bg-black/40 z-50 flex items-end sm:items-center justify-center"><div className="bg-card rounded-t-2xl sm:rounded-2xl p-6 w-full max-w-2xl max-h-[85vh] overflow-y-auto"><h2 className="text-xl font-bold mb-6">Follower Analytics</h2><div className="grid md:grid-cols-2 gap-4"><div className="bg-muted/30 rounded-xl p-4"><h3 className="font-medium mb-4">Faculty Distribution</h3><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={facultyData} dataKey="value" outerRadius={75} label>{facultyData.map((entry, index) => <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div><div className="bg-muted/30 rounded-xl p-4"><h3 className="font-medium mb-4">Year of Study</h3><ResponsiveContainer width="100%" height={240}><BarChart data={yearData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="year" /><YAxis /><Tooltip /><Bar dataKey="count" fill="#D4AF37" radius={[8, 8, 0, 0]} /></BarChart></ResponsiveContainer></div></div><button onClick={onClose} className="w-full mt-6 px-4 py-3 bg-primary text-primary-foreground rounded-xl">Close</button></div></div>; }
