import { CheckCircle, X } from "lucide-react";
import { useState } from "react";
import { pendingClubs } from "../../data/mockClubs";

export default function AdminClubModeration() {
  const [selected, setSelected] = useState(pendingClubs[0]);
  const [reason, setReason] = useState("");
  return <div className="max-w-5xl mx-auto px-4 py-6"><h1 className="text-2xl font-bold">Admin Club Moderation</h1><p className="text-muted-foreground mb-6">Review club verification submissions</p><div className="grid md:grid-cols-3 gap-6"><aside className="space-y-2">{pendingClubs.map((club) => <button key={club.id} onClick={() => setSelected(club)} className={`w-full p-4 rounded-xl border text-left ${selected?.id === club.id ? "border-primary bg-primary/5" : "border-border bg-card"}`}><h2 className="font-semibold">{club.name}</h2><p className="text-xs text-muted-foreground">{club.category}</p></button>)}</aside><main className="md:col-span-2 bg-card rounded-xl border border-border p-6">{selected && <><div className="w-20 h-20 bg-primary rounded-2xl text-white grid place-items-center text-2xl font-bold mb-4">{selected.name.slice(0, 2).toUpperCase()}</div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-sm text-muted-foreground mb-4">Submitted by {selected.submittedBy}</p><div className="bg-muted/30 rounded-xl p-4 mb-4"><p><b>Category:</b> {selected.category}</p><p><b>Reason:</b> {selected.reason}</p></div><textarea value={reason} onChange={(e) => setReason(e.target.value)} rows={4} className="w-full px-4 py-3 bg-background rounded-lg border border-border mb-4" placeholder="Rejection reason or admin note..." /><div className="flex gap-3"><button className="flex-1 py-3 bg-green-600 text-white rounded-lg flex justify-center gap-2"><CheckCircle className="w-5 h-5" />Approve & Verify</button><button className="flex-1 py-3 bg-red-600 text-white rounded-lg flex justify-center gap-2"><X className="w-5 h-5" />Reject</button></div></>}</main></div></div>;
}
